version: "3.3"

services:
  # NETWORK MANAGEMENT
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: "always"
    network_mode: "host"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.myresolver.acme.email=axel.ottin@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--pilot.token=f5535d84-95ae-43bb-9305-165816ad401a"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=N3IU6tsQRiunSL5z"
      - "OVH_APPLICATION_SECRET=RiFtWYBme1MFBmmldtmwZ9QehUVU0exw"
      - "OVH_CONSUMER_KEY=jc3l129ypXhQSK52l8tZFBnc5Fh4ERgs"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.aisuru.fr`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=9000"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=root:$$2y$$05$$V4wO7wcdULhVtR1Q6g/oz.HgBfYCx97eBu8PuyIA/2Mkh7o/aCfVC"

      # Redirect http to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web" 
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"


  # CONTAINER MANAGEMENT
  portainer:
    image: "portainer/portainer-ce"    
    container_name: "portainer"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer/config:/data"
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.aisuru.fr`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"


  # MEDIA SERVER
  plex:
    image: "ghcr.io/linuxserver/plex"
    container_name: "plex"
    network_mode: "host"
    restart: "always"
    volumes:
      - "/mnt/plex-storage/data/media:/data/media"
      - "/mnt/plex-storage/config:/config"
    environment:
      - "VERSION=latest"
      - "PUID=0"
      - "PGID=0"
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.aisuru.fr`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.http.routers.plex.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=root:$$2y$$05$$V4wO7wcdULhVtR1Q6g/oz.HgBfYCx97eBu8PuyIA/2Mkh7o/aCfVC"


  # PLEX CONTENT REQUESTS
  ombi:
    image: "ghcr.io/linuxserver/ombi"
    container_name: "ombi"
    restart: "always"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "TZ=Europe/Paris"
    network_mode: "service:transmission"
    depends_on:
      - transmission
    volumes:
      - "./ombi/config:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"
      - "traefik.http.routers.ombi.rule=Host(`ombi.aisuru.fr`)"
      - "traefik.http.routers.ombi.entrypoints=websecure"
      - "traefik.http.routers.ombi.tls.certresolver=myresolver"


  # PLEX STATS & ADMIN
  tautulli:
    image: "ghcr.io/linuxserver/tautulli"
    container_name: "tautulli"
    restart: "always"
    environment:
      - "PUID=0"
      - "PGID=0"
      - "TZ=Europe/Paris"
    volumes:
      - "./tautulli/config:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.aisuru.fr`)"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.tls.certresolver=myresolver"


  # TORRENTS DOWNLOADER WITH RSS
  rtorrent:
    image: "wonderfall/rtorrent-flood"
    container_name: "rtorrent"
    restart: "always"
    tty: "true"
    network_mode: "service:transmission"
    depends_on:
      - transmission
    security_opt:
      - "no-new-privileges:true"
    environment:
      - "UID=0"
      - "GID=0"
      - "FLOOD_SECRET=sf*Gy'+~6h}R&dB'2T/b@=nCb?A%.a"
      - "DISABLE_AUTH=false"
      - "RTORRENT_SCGI=5000"
    volumes:
      - "./rtorrent-flood:/flood-db"
      - "/mnt/plex-storage/data/torrents:/data/torrents"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rtorrent.loadbalancer.server.port=3000"
      - "traefik.http.routers.rtorrent.rule=Host(`rtorrent.aisuru.fr`)"
      - "traefik.http.routers.rtorrent.entrypoints=websecure"
      - "traefik.http.routers.rtorrent.service=rtorrent"
      - "traefik.http.routers.rtorrent.tls.certresolver=myresolver"


  # TORRENT DOWNLOADER WITH VPN
  transmission:
    image: "haugene/transmission-openvpn"
    container_name: "transmission"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "/mnt/ssd-storage/docker/seedbox/transmission/watch:/data/watch"
      - "/mnt/plex-storage/data/torrents:/data/torrents"
      - "/mnt/ssd-storage/docker/seedbox/transmission/home:/data/transmission-home"
    environment:
      - "TRANSMISSION_WEB_UI=flood-for-transmission"
      - "OPENVPN_PROVIDER=NORDVPN"
      - "NORDVPN_COUNTRY=FR"
      - "NORDVPN_CATEGORY=legacy_p2p"
      - "NORDVPN_PROTOCOL=tcp"
      - "OPENVPN_USERNAME=axel.ottin@gmail.com"
      - "OPENVPN_PASSWORD=16Adf1995Axel*_?*"
      - "LOCAL_NETWORK=192.168.0.0/24"
      - "TZ=Europe/Paris"
      - "ENABLE_UFW=true"
      - "UFW_ALLOW_GW_NET=true"
      - "UFW_EXTRA_PORTS=3000,3579,7878,8989,9117,49184"
      - "PGID=0"
      - "PUID=0"
      - "TRANSMISSION_DOWNLOAD_DIR=/data/torrents"
      - "TRANSMISSION_INCOMPLETE_DIR=/data/torrents"
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - "3000:3000"
      - "3579:3579"
      - "7878:7878"
      - "8989:8989"
      - "9117:9117"
      - "49184:49184"
      - "49184:49184/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.rule=Host(`flood.aisuru.fr`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
      - "traefik.http.routers.transmission.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=root:$$2y$$05$$V4wO7wcdULhVtR1Q6g/oz.HgBfYCx97eBu8PuyIA/2Mkh7o/aCfVC"


  # TRACKER INDEXER
  jackett:
    image: "ghcr.io/linuxserver/jackett"
    container_name: "jackett"
    restart: "always"
    network_mode: "service:transmission"
    depends_on:
      - transmission
    volumes:
      - "./jackett/config:/config"
      - "/mnt/plex-storage/data/torrents:/downloads"
    environment:
      - "TZ=Europe/Paris"
      - "AUTO_UPDATE=true"
      - "PGID=0"
      - "PUID=0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.jackett.rule=Host(`jackett.aisuru.fr`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
      - "traefik.http.routers.jackett.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=root:$$2y$$05$$V4wO7wcdULhVtR1Q6g/oz.HgBfYCx97eBu8PuyIA/2Mkh7o/aCfVC"


  # MOVIES MONITOR
  radarr:
    image: "ghcr.io/linuxserver/radarr"
    container_name: "radarr"
    restart: "always"
    network_mode: "service:transmission"
    depends_on:
      - transmission
    volumes:
      - "./radarr/config:/config"
      - "/mnt/plex-storage/data:/data"
    environment:
      - "PGID=0"
      - "PUID=0"
      - "TZ=Europe/Paris"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.aisuru.fr`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"


  # TV SHOWS AND ANIMES MONITOR
  sonarr:
    image: "ghcr.io/linuxserver/sonarr"
    container_name: "sonarr"
    restart: "always"
    network_mode: "service:transmission"
    depends_on:
      - transmission
    volumes:
      - "./sonarr/config:/config"
      - "/mnt/plex-storage/data:/data"
    environment:
      - "PGID=0"
      - "PUID=0"
      - "TZ=Europe/Paris"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.aisuru.fr`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"

  # Graph and monitoring
  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana"
    restart: "always"
    environment:
      - "GF_SECURITY_ADMIN_USER=root"
      - "GF_SECURITY_ADMIN_PASSWORD=Yokidoki59*"
      - "GF_USERS_ALLOW_SIGN_UP=false"

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.aisuru.fr`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"